-- currently spawning 1 squad per smart
-- defined stalkers spawn first, then random stalkers, then mutants

-- any need to remove from "raid_squads_t" on unregister? i think not

raid_squads_t = {}
local raid_sim_spawned = false

rank_limit_t = {
	-- stalkers
	renegade = { 1, 2 }, bandit = { 1, 3 }, stalker = { 1, 4 }, csky = { 1, 4 }, freedom = { 2, 4 },
	duty = { 2, 4 }, army = { 2, 4 }, killer = { 3, 4 }, monolith = { 3, 4 }, zombied = { 1, 4 }, ecolog = { 1, 3 },

	-- mutants
	dog = { 1, 2 }, cat = { 1, 2 }, zombie = { 1, 2 }, flesh = { 1, 2 }, boar = { 1, 3 }, fracture = { 1, 3 },
	pseudodog = { 1, 3 }, lurker = { 1 , 3 }, snork = { 2, 3 }, bloodsucker = { 1, 3 }, psy_dog = { 3, 3 },
	burer = { 2, 4 }, psysucker = { 3, 3 }, chimera = { 2, 3 }, gigant = { 3, 3 }, controller = { 3, 3 }, poltergeist = { 3, 3 },
	alpha_chimera = { 3, 3 }, alpha_giant = { 3, 3 }, alpha_bloodsucker = { 3, 3 }, alpha_burer = { 3, 3 },
}

raid_sim_t = {
	-------------------- T1
	--27 smart
	["k00_marsh"] = {
		level_tier = 1,
		stalkers = {
			renegade = {
				[1] = { min = 1, max = 2, idle = 1 },
			},
			bandit = {
				[1] = { min = 1, max = 1, idle = 0 },
			},
			csky = {
				[1] = { min = 0, max = 1, idle = 0 },
			},
			random = { squads = {"freedom", "duty", "stalker", "none"}, num = 1 },
		},
		mutants = {
			-- predator battle preset
			[1] = { 
				dog = { min = 2, max = 3, idle = 2 },
				pseudodog = { min = 1, max = 1, idle = 1 },
				cat = { min = 2, max = 3, idle = 2 },
				lurker = { min = 1, max = 1, idle = 1 },
			},
			-- hunting (c) battle preset
			[2] = {
				flesh = { min = 2, max = 3, idle = 2 },
				boar = { min = 1, max = 1, idle = 1 },
				cat = { min = 2, max = 3, idle = 2 },
				lurker = { min = 1, max = 1, idle = 0 },
			},
			-- hunting (d) preset
			[3] = {
				flesh = { min = 2, max = 3, idle = 2 },
				boar = { min = 1, max = 1, idle = 1 },
				dog = { min = 2, max = 3, idle = 2 },
				pseudodog = { min = 1, max = 1, idle = 0 },
			},
			-- migration (p) preset + marsh bloodsucker
			[4] = {
				zombie = { min = 3, max = 4, idle = 2 },
				fracture = { min = 2, max = 3, idle = 2 },
				bloodsucker = { min = 1, max = 1, idle = 0 },
				boar = { min = 1, max = 1, idle = 0 },
			},
			-- migration non-predator preset + marsh bloodsucker
			[5] = {
				flesh = { min = 4, max = 5, idle = 3 },
				boar = { min = 1, max = 2, idle = 2 },
				bloodsucker = { min = 1, max = 1, idle = 0 },
			},
		},
	},

	--37 smart
	["poselok_ug"] = {
		level_tier = 1,
		stalkers = {
			bandit = {
				[1] = { min = 1, max = 2, idle = 0 },
			},
			renegade = {
				[1] = { min = 1, max = 2, idle = 1 },
			},

			stalker = {
				[1] = { min = 1, max = 1, idle = 0 },
				[2] = { min = 0, max = 1, idle = 0 },
			},
			random = { squads = {"renegade", "freedom", "duty", "none"}, num = 1 },
		},
		mutants = {
			-- predator battle preset
			[1] = { 
				dog = { min = 2, max = 3, idle = 1 },
				pseudodog = { min = 1, max = 2, idle = 1 },
				cat = { min = 2, max = 3, idle = 1 },
				lurker = { min = 1, max = 2, idle = 1 },
			},
			-- hunting (c) battle preset
			[2] = {
				flesh = { min = 2, max = 4, idle = 2 },
				boar = { min = 1, max = 2, idle = 1 },
				cat = { min = 2, max = 3, idle = 1 },
				lurker = { min = 1, max = 2, idle = 0 },
			},
			-- hunting (d) preset
			[3] = {
				flesh = { min = 3, max = 4, idle = 2 },
				boar = { min = 1, max = 2, idle = 1 },
				dog = { min = 2, max = 3, idle = 1 },
				pseudodog = { min = 1, max = 2, idle = 0 },
			},
			-- psi-mutants vs dogs preset 
			[4] = {
				zombie = { min = 4, max = 5, idle = 2 },
				fracture = { min = 2, max = 3, idle = 1 },
				dog = { min = 2, max = 3, idle = 2 },
				pseudodog = { min = 1, max = 2, idle = 1 },
			},
		},
	},
	
	--21 smart
	["l03_agroprom"] = {
		level_tier = 1,
		stalkers = {
			army = {
				[2] = { min = 1, max = 2, idle = 1 },
			},
			stalker = {
				[1] = { min = 0, max = 1, idle = 0 },
			},
			random = { squads = {"killer", "renegade", "army", "freedom", "duty", "none"}, num = 1 },
		},
		mutants = {
			-- predator battle preset
			[1] = { 
				dog = { min = 1, max = 2, idle = 2 },
				pseudodog = { min = 1, max = 1, idle = 1 },
				cat = { min = 1, max = 2, idle = 2 },
				lurker = { min = 1, max = 1, idle = 1 },
			},
			-- hunting (c) battle preset
			[2] = {
				flesh = { min = 2, max = 3, idle = 2 },
				boar = { min = 1, max = 1, idle = 1 },
				cat = { min = 1, max = 2, idle = 1 },
				lurker = { min = 1, max = 2, idle = 0 },
			},
			-- hunting (d) preset
			[3] = {
				flesh = { min = 2, max = 3, idle = 2 },
				boar = { min = 1, max = 1, idle = 1 },
				dog = { min = 1, max = 2, idle = 1 },
				pseudodog = { min = 1, max = 2, idle = 0 },
			},
			-- psi-mutants vs predator battle preset
			[4] = {
				fracture = { min = 1, max = 2, idle = 1 },
				snork = { min = 2, max = 2, idle = 1 },
				cat = { min = 1, max = 2, idle = 1 },
				lurker = { min = 1, max = 2, idle = 1 },
			},
		},
	},

	--21 smart
	["l01_escape"] = {
		level_tier = 1,
		stalkers = {
			bandit = {
				[1] = { min = 2, max = 2, idle = 1 },
			},
			stalker = {
				[1] = { min = 0, max = 1, idle = 0 },
			},
			random = { squads = {"bandit", "army", "stalker", "csky", "none"}, num = 1 },
		},
		mutants = {
			-- predator battle preset
			[1] = { 
				dog = { min = 1, max = 2, idle = 1 },
				pseudodog = { min = 1, max = 1, idle = 0 },
				cat = { min = 1, max = 2, idle = 1 },
				lurker = { min = 1, max = 1, idle = 1 },
			},
			-- hunting (c) battle preset
			[2] = {
				flesh = { min = 2, max = 3, idle = 2 },
				boar = { min = 1, max = 1, idle = 1 },
				cat = { min = 1, max = 2, idle = 1 },
				lurker = { min = 1, max = 1, idle = 1 },
			},
			-- hunting (d) preset
			[3] = {
				flesh = { min = 2, max = 3, idle = 2 },
				boar = { min = 1, max = 1, idle = 1 },
				dog = { min = 1, max = 2, idle = 1 },
				pseudodog = { min = 1, max = 1, idle = 0 },
			},
		},
	},

	-------------------- T2
	--21 smart
	["k02_trucks_cemetery"] = {
		level_tier = 2,
		stalkers = {
			renegade = {
				[2] = { min = 1, max = 2, idle = 1 },
			},
			duty = {
				[2] = { min = 0, max = 1, idle = 0 },
			},
			freedom = {
				[2] = { min = 0, max = 1, idle = 0 },
			},
			random = { squads = {"bandit", "renegade", "freedom", "duty", "stalker", "none"}, num = 1 },
		},
		mutants = {
			-- predator battle preset
			[1] = { 
				dog = { min = 1, max = 2, idle = 1 },
				pseudodog = { min = 1, max = 2, idle = 1 },
				cat = { min = 1, max = 2, idle = 1 },
				lurker = { min = 1, max = 2, idle = 1 },
			},
			-- hunting (c) battle preset
			[2] = {
				flesh = { min = 2, max = 3, idle = 2 },
				boar = { min = 1, max = 2, idle = 1 },
				cat = { min = 1, max = 2, idle = 1 },
				lurker = { min = 1, max = 2, idle = 0 },
				bloodsucker = { min = 1, max = 1, idle = 0 },
			},
			-- hunting (d) preset
			[3] = {
				flesh = { min = 2, max = 3, idle = 2 },
				boar = { min = 1, max = 2, idle = 1 },
				dog = { min = 1, max = 2, idle = 1 },
				pseudodog = { min = 2, max = 3, idle = 0 },
				gigant = { min = 0, max = 1, idle = 0 },
			},
			-- migration (non-predator) preset + gigant
			[4] = {
				flesh = { min = 4, max = 5, idle = 2 },
				boar = { min = 2, max = 3, idle = 1 },
				gigant = { min = 1, max = 1, idle = 1 },
			},
		},
	},

	--19 smart
	["l02_garbage"] = {
		level_tier = 2,
		stalkers = {
			bandit = {
				[2] = { min = 1, max = 2, idle = 1 },
			},
			stalker = {
				[2] = { min = 0, max = 1, idle = 0 },
			},
			duty = {
				[2] = { min = 0, max = 1, idle = 1 },
			},
			random = { squads = {"killer", "bandit", "freedom", "stalker", "none"}, num = 1 },
		},
		mutants = {
			-- predator battle preset
			[1] = { 
				dog = { min = 0, max = 1, idle = 1 },
				pseudodog = { min = 1, max = 2, idle = 1 },
				cat = { min = 0, max = 1, idle = 1 },
				lurker = { min = 1, max = 2, idle = 1 },
				psy_dog = { min = 0, max = 1, idle = 1 },
			},
			-- hunting (c) battle preset
			[2] = {
				flesh = { min = 2, max = 3, idle = 2 },
				boar = { min = 1, max = 2, idle = 1 },
				cat = { min = 1, max = 2, idle = 1 },
				lurker = { min = 1, max = 2, idle = 0 },
			},
			-- hunting (d) preset
			[3] = {
				flesh = { min = 2, max = 3, idle = 2 },
				boar = { min = 1, max = 2, idle = 1 },
				dog = { min = 1, max = 2, idle = 1 },
				pseudodog = { min = 1, max = 1, idle = 0 },
				psy_dog = { min = 1, max = 1, idle = 1 },
			},
		},
	},

	--15 smart
	["promzona"] = {
		level_tier = 2,
		stalkers = {
			stalker = {
				[2] = { min = 1, max = 2, idle = 0 },
			},		
			killer = {
				[2] = { min = 0, max = 1, idle = 0 },
			},
			random = { squads = {"killer", "army", "csky", "stalker", "none"}, num = 1 },
		},
		mutants = {
			-- psi-mutants vs predators preset
			[1] = {
				fracture = { min = 1, max = 2, idle = 1 },
				snork = { min = 1, max = 1, idle = 1 },
				burer = { min = 1, max = 1, idle = 0 },
				lurker = { min = 1, max = 2, idle = 2 },
				bloodsucker = { min = 1, max = 1, idle = 0 },
			},
			-- psi-mutants migration preset
			[2] = { 
				zombie = { min = 3, max = 4, idle = 3 },
				fracture = { min = 2, max = 3, idle = 2 },
				snork = { min = 1, max = 1, idle = 0 },
				burer = { min = 1, max = 1, idle = 1 },
			},
			-- hunting (p) battle preset
			[3] = {
				flesh = { min = 1, max = 2, idle = 2 },
				boar = { min = 1, max = 2, idle = 1 },
				fracture = { min = 1, max = 2, idle = 2 },
				snork = { min = 1, max = 1, idle = 0 },
				burer = { min = 1, max = 1, idle = 1 },
			},
			-- hunting (d) preset
			[4] = {
				flesh = { min = 1, max = 2, idle = 2 },
				boar = { min = 1, max = 2, idle = 1 },
				dog = { min = 1, max = 2, idle = 1 },
				pseudodog = { min = 1, max = 1, idle = 0 },
				psy_dog = { min = 1, max = 1, idle = 1 },
			},
		},
	},

	--20 smart
	["l04_darkvalley"] = {
		level_tier = 2,
		stalkers = {
			bandit = {
				[2] = { min = 1, max = 2, idle = 1 },
			},
			stalker = {
				[2] = { min = 0, max = 1, idle = 0 },
				[3] = { min = 0, max = 1, idle = 0 },
			},
			random = { squads = {"killer", "army", "stalker", "csky", "none"}, num = 2 },
		},
		mutants = {
			-- psi-mutants vs predators preset
			[1] = {
				fracture = { min = 1, max = 2, idle = 2 },
				snork = { min = 1, max = 2, idle = 1 },
				burer = { min = 0, max = 1, idle = 0 },
				lurker = { min = 1, max = 2, idle = 1 },
				bloodsucker = { min = 1, max = 1, idle = 0 },
				poltergeist = { min = 0, max = 1, idle = 0 },
			},
			-- psi-mutants migration preset
			[2] = { 
				zombie = { min = 3, max = 4, idle = 3 },
				fracture = { min = 2, max = 3, idle = 2 },
				snork = { min = 1, max = 2, idle = 0 },
				burer = { min = 0, max = 1, idle = 1 },
				poltergeist = { min = 0, max = 1, idle = 0 },
			},
			-- hunting (p) battle preset
			[3] = {
				flesh = { min = 2, max = 3, idle = 2 },
				boar = { min = 1, max = 2, idle = 1 },
				fracture = { min = 2, max = 3, idle = 2 },
				snork = { min = 1, max = 2, idle = 0 },
				burer = { min = 0, max = 1, idle = 0 },
			},
			-- hunting (d) preset
			[4] = {
				flesh = { min = 2, max = 3, idle = 2 },
				boar = { min = 1, max = 2, idle = 1 },
				dog = { min = 1, max = 2, idle = 2 },
				pseudodog = { min = 1, max = 2, idle = 0 },
				burer = { min = 1, max = 1, idle = 0 },
			},
		},
	},

	-------------------- T3
	--17 smart
	["l07_military"] = {
		level_tier = 3,
		stalkers = {
			freedom = {
				[3] = { min = 1, max = 1, idle = 0 },
			},
			duty = {
				[3] = { min = 1, max = 1, idle = 0 },
			},
			zombied = {
				[2] = { min = 1, max = 2, idle = 2 },
				[3] = { min = 1, max = 1, idle = 2 },
			},
			random = { squads = {"duty", "freedom", "killer", "stalker", "none"}, num = 1 },
		},
		mutants = {
			-- psi-mutants vs predators preset
			[1] = {
				snork = { min = 1, max = 2, idle = 1 },
				controller = { min = 1, max = 1, idle = 1 },
				lurker = { min = 1, max = 2, idle = 1 },
				bloodsucker = { min = 1, max = 1, idle = 1 },
				psysucker = { min = 1, max = 1, idle = 0 },
			},
			-- psi-mutants migration preset
			[2] = { 
				zombie = { min = 2, max = 3, idle = 3 },
				fracture = { min = 2, max = 3, idle = 3 },
				snork = { min = 1, max = 2, idle = 0 },
				controller = { min = 1, max = 1, idle = 1 },
			},
			-- hunting (p) battle preset
			[3] = {
				flesh = { min = 2, max = 3, idle = 2 },
				boar = { min = 1, max = 2, idle = 1 },
				fracture = { min = 1, max = 2, idle = 2 },
				snork = { min = 1, max = 2, idle = 0 },
				burer = { min = 1, max = 1, idle = 0 },
			},
			-- hunting (d) preset
			[4] = {
				flesh = { min = 1, max = 2, idle = 1 },
				boar = { min = 1, max = 2, idle = 2 },
				dog = { min = 1, max = 2, idle = 2 },
				pseudodog = { min = 2, max = 3, idle = 0 },
			},
		},
	},

	--17 smart
	["grimwood"] = {
		level_tier = 3,
		stalkers = {
			killer = {
				[3] = { min = 0, max = 1, idle = 1 },
			},
			csky = {
				[3] = { min = 0, max = 1, idle = 1 },
			},
			random = { squads = {"csky", "killer", "army", "stalker", "none"}, num = 1 },
		},
		mutants = {
			-- luring preset
			[1] = {
				flesh = { min = 2, max = 3, idle = 5 },
				boar = { min = 2, max = 3, idle = 4 },
				gigant = { min = 0, max = 1, idle = 1 },
				bloodsucker = { min = 1, max = 2, idle = 2 },
			},
			-- feast (с) preset
			[2] = { 
				flesh = { min = 1, max = 2, idle = 3 },
				boar = { min = 1, max = 2, idle = 3 },
				gigant = { min = 0, max = 1, idle = 0 },
				lurker = { min = 1, max = 2, idle = 1 },
				chimera = { min = 1, max = 1, idle = 1 },
			},
			-- feast (d) preset
			[3] = {
				flesh = { min = 1, max = 2, idle = 3 },
				boar = { min = 1, max = 2, idle = 3 },
				gigant = { min = 0, max = 1, idle = 0 },
				pseudodog = { min = 2, max = 3, idle = 2 },
				psy_dog = { min = 1, max = 1, idle = 1 },
			},
		},
	},

	--15 smart
	["l10_red_forest"] = {
		level_tier = 3,
		stalkers = {
			killer = {
				[3] = { min = 0, max = 1, idle = 1 },
			},
			stalker = {
				[3] = { min = 0, max = 1, idle = 1 },
			},
			random = { squads = {"killer", "army", "freedom", "duty", "stalker", "none"}, num = 1 },
		},
		mutants = {
			-- predator battle preset
			[1] = { 
				pseudodog = { min = 1, max = 2, idle = 2 },
				psy_dog = { min = 1, max = 1, idle = 1 },
				lurker = { min = 1, max = 2, idle = 2 },
				bloodsucker = { min = 1, max = 1, idle = 0 },
				chimera = { min = 0, max = 1, idle = 1 },
			},
			-- hunting (c) battle preset
			[2] = {
				flesh = { min = 2, max = 3, idle = 2 },
				lurker = { min = 1, max = 2, idle = 1 },
				bloodsucker = { min = 1, max = 2, idle = 1 },
				chimera = { min = 0, max = 1, idle = 0 },
			},
			-- hunting (d) preset
			[3] = {
				flesh = { min = 2, max = 3, idle = 2 },
				pseudodog = { min = 2, max = 3, idle = 2 },
				psy_dog = { min = 1, max = 1, idle = 1 },
				chimera = { min = 0, max = 1, idle = 0 },
			},
		},
	},

	--53 smart
	["jupiter"] = {
		level_tier = 3,
		stalkers = {
			killer = {
				[3] = { min = 1, max = 2, idle = 0 },
			},
			monolith = {
				[3] = { min = 1, max = 2, idle = 2 },
			},
			zombied = {
				[2] = { min = 2, max = 3, idle = 1 },
				[3] = { min = 2, max = 3, idle = 1 },
			},
			random = { squads = {"zombied", "killer", "army", "freedom", "duty", "stalker", "none"}, num = 2 },
		},
		mutants = {
			-- psi-mutants vs predators preset
			[1] = {
				snork = { min = 2, max = 3, idle = 2 },
				burer = { min = 1, max = 2, idle = 2 },
				controller = { min = 1, max = 1, idle = 1 },
				lurker = { min = 3, max = 4, idle = 2 },
				bloodsucker = { min = 1, max = 1, idle = 0 },
				psysucker = { min = 2, max = 3, idle = 1 },
			},
			-- psi-mutants migration preset
			[2] = { 
				zombie = { min = 4, max = 5, idle = 4 },
				burer = { min = 1, max = 2, idle = 0 },
				snork = { min = 2, max = 3, idle = 2 },
				controller = { min = 1, max = 1, idle = 1 },
				poltergeist = { min = 0, max = 1, idle = 0 },
				psysucker = { min = 2, max = 3, idle = 0 },
			},
			-- hunting (p) battle preset
			[3] = {
				flesh = { min = 2, max = 3, idle = 0 },
				boar = { min = 1, max = 2, idle = 0 },
				burer = { min = 1, max = 2, idle = 0 },
				snork = { min = 2, max = 3, idle = 2 },
				controller = { min = 1, max = 1, idle = 1 },
				psysucker = { min = 2, max = 3, idle = 0 },
			},
		},
	},

	--58 smart
	["zaton"] = {
		level_tier = 4,
		stalkers = {
			killer = {
				[4] = { min = 1, max = 2, idle = 0 },
			},
			monolith = {
				[4] = { min = 3, max = 4, idle = 2 },
			},
			zombied = {
				[2] = { min = 2, max = 3, idle = 2 },
				[3] = { min = 2, max = 3, idle = 2 },
			},
			random = { squads = {"army", "freedom", "duty", "stalker", "none"}, num = 2 },
		},
		mutants = {
			-- psi-mutants vs predators preset
			[1] = {
				snork = { min = 3, max = 4, idle = 3 },
				burer = { min = 3, max = 4, idle = 1 },
				controller = { min = 1, max = 2, idle = 1 },
				lurker = { min = 3, max = 4, idle = 3 },
				bloodsucker = { min = 3, max = 4, idle = 2 },
				psysucker = { min = 2, max = 3, idle = 0 },
				chimera = { min = 2, max = 3, idle = 1 },
			},
			-- psi-mutants domination preset
			[2] = { 
				snork = { min = 5, max = 6, idle = 4 },
				burer = { min = 4, max = 5, idle = 3 },
				controller = { min = 2, max = 2, idle = 1 },
				psysucker = { min = 1, max = 2, idle = 0 },
				chimera = { min = 2, max = 3, idle = 1 },
			},
			-- predators domination preset
			[3] = {
				boar = { min = 3, max = 4, idle = 0 },
				burer = { min = 2, max = 3, idle = 1 },
				lurker = { min = 5, max = 6, idle = 4 },
				bloodsucker = { min = 1, max = 2, idle = 1 },
				chimera = { min = 2, max = 3, idle = 2 },
				psysucker = { min = 1, max = 2, idle = 0 },
			},
		},
	},

	--38 smart
	["pripyat"] = {
		level_tier = 4,
		stalkers = {
			monolith = {
				[3] = { min = 2, max = 3, idle = 2 },
			},
			zombied = {
				[3] = { min = 2, max = 3, idle = 2 },
			},
			random = { squads = {"killer", "army", "stalker", "none"}, num = 2 },
		},
		mutants = {
			-- psi-mutants vs predators preset
			[1] = {
				snork = { min = 2, max = 3, idle = 3 },
				burer = { min = 1, max = 2, idle = 1 },
				controller = { min = 0, max = 1, idle = 1 },
				lurker = { min = 1, max = 2, idle = 3 },
				bloodsucker = { min = 1, max = 1, idle = 1 },
				psysucker = { min = 1, max = 1, idle = 1 },
				chimera = { min = 1, max = 2, idle = 1 },
			},
			-- psi-mutants domination preset
			[2] = { 
				snork = { min = 3, max = 4, idle = 3 },
				burer = { min = 1, max = 2, idle = 2 },
				controller = { min = 0, max = 1, idle = 1 },
				psysucker = { min = 1, max = 2, idle = 0 },
				chimera = { min = 2, max = 2, idle = 1 },
			},
			-- predators domination preset
			[3] = {
				burer = { min = 1, max = 2, idle = 2 },
				lurker = { min = 3, max = 4, idle = 3 },
				bloodsucker = { min = 2, max = 2, idle = 1 },
				chimera = { min = 1, max = 2, idle = 2 },
				psysucker = { min = 2, max = 2, idle = 0 },
			},
		},
	},

}

function raid_start_spawn(level_name)

	-- check if this level exists (for addons)
	if not (level and raid_utils.level_exist(level_name)) then return end

	-- dup table of this level
	local squads_t = raid_sim_t[level_name] and dup_table(raid_sim_t[level_name])
	if not squads_t then return end


	-- collect all smarts on picked level (except smarts busy by tasks and events)
	local smarts_t = raid_utils.find_random_smart(level_name, true, "all")
	if (not smarts_t) then return end


	-- Stalkers spawn
	-- set how many stalkers to spawn
	for faction, t in pairs(squads_t.stalkers) do
		for tier, t2 in pairs(t) do
			if faction ~= "random" then
				squads_t.stalkers[faction][tier].spawn_num = math.ceil( math.random(t2.min, t2.max) * raid_tables.simulation_spawn_mult )
				printf(" - set stalkers [%s] tier [%s] to spawn amount [%s]", faction, tier, squads_t.stalkers[faction][tier].spawn_num)
			end
		end
	end

	-- spawn stalkers
	for faction, t in pairs(squads_t.stalkers) do
		if faction ~= "random" then
			for tier, t2 in pairs(t) do
				if t2.spawn_num > 0 then
					for i = 1, t2.spawn_num do
						local squad_sec = "raid_" .. faction .. "_sim_squad_" .. tier
						local comm = squad_sec and ini_sys:section_exist(squad_sec) and ini_sys:r_string_ex(squad_sec, "faction")

						-- pick random viable smart
						local smart = raid_utils.find_viable_smart(smarts_t, comm, nil, true)
						if smart then

							-- spawn squad
							local squad = spawn_raid_sim_squad(smart.id, squad_sec)

							-- store squad
							if squad then
								-- make it "idle" if possible
								if squads_t.stalkers[faction][tier].idle > 0 then
									squad.scripted_target = smart:name()
									raid_squads_t[squad.id] = smart:name()
									squads_t.stalkers[faction][tier].idle = squads_t.stalkers[faction][tier].idle - 1
								else
									squad.idle_time = 0
									raid_squads_t[squad.id] = "walking"
								end
								printf("- spawn stalker squad [%s] on smart [%s]", squad_sec, smart:name())
							end

							-- remove smart from the table (spawn 1 squad per smart)
							smarts_t[smart.id] = nil
						end

					end
				end
			end
		end
	end


	-- then spawn random stalkers
	local new_stalkers_random_num = math.ceil(squads_t.stalkers.random.num * raid_tables.simulation_spawn_mult)
	for i = 1, new_stalkers_random_num do
		local ar = squads_t.stalkers.random.squads
		local random_squad_faction = ar[math.random(1, #ar)]

		if random_squad_faction ~= "none" then

			-- adjust rank to level tier
			local squad_tier = squads_t.level_tier
			if squad_tier < rank_limit_t[random_squad_faction][1] then
				squad_tier = rank_limit_t[random_squad_faction][1]
			elseif squad_tier > rank_limit_t[random_squad_faction][2] then
				squad_tier = rank_limit_t[random_squad_faction][2]
			end

			local squad_sec = squad_tier and ("raid_" .. random_squad_faction .. "_sim_squad_" .. squad_tier)
			local comm = squad_sec and ini_sys:section_exist(squad_sec) and ini_sys:r_string_ex(squad_sec, "faction")

			-- pick random viable smart
			local smart = raid_utils.find_viable_smart(smarts_t, comm, nil, true)
			if smart then		-- check for spawned stuff on this smart here

				-- spawn squad
				local squad = spawn_raid_sim_squad(smart.id, squad_sec)

				-- store squad
				if squad then
					-- random squads are always walking
					squad.idle_time = 0
					raid_squads_t[squad.id] = "walking"
					printf("~ spawn random stalker squad [%s] on smart [%s]", squad_sec, smart:name())
				end

				-- remove smart from the table (spawn 1 squad per smart)
				smarts_t[smart.id] = nil

			end
		end

	end


	-- Mutant spawn
	-- pick random preset
	local preset = math.random(1, #squads_t.mutants)

	-- set how many mutants to spawn
	for faction, t in pairs(squads_t.mutants[preset]) do
		squads_t.mutants[preset][faction].spawn_num = math.ceil( math.random(t.min, t.max) * raid_tables.simulation_spawn_mult )
		printf(" - set mutants [%s] to spawn amount [%s]", faction, squads_t.mutants[preset][faction].spawn_num)
	end

	-- then spawn mutants
	for faction, t in pairs(squads_t.mutants[preset]) do
		if t.spawn_num > 0 then
			for i = 1, t.spawn_num do

				-- adjust rank to level tier
				local squad_tier = squads_t.level_tier
				if squad_tier < rank_limit_t[faction][1] then
					squad_tier = rank_limit_t[faction][1]
				elseif squad_tier > rank_limit_t[faction][2] then
					squad_tier = rank_limit_t[faction][2]
				end

				local squad_sec = "raid_simulation_" .. faction .. "_" .. squad_tier

              
				local night_bonus = 0
                if (level.get_time_hours() >= 22 or level.get_time_hours() < 4) then night_bonus = 20 end
                -- random chance to increment rank Mutant
                if (math.random(1, 100) <= (25 + night_bonus)) then 
					local new_squad_sec = "raid_simulation_" .. faction .. "_" .. (squad_tier + 1)
					if ini_sys:section_exist(new_squad_sec) then
						squad_sec = new_squad_sec
						printf("mutant spawn, random rank incr for [%s], new squad [%s]", squad_sec, new_squad_sec)
					end
				end

				-- pick random viable smart
				local smart = raid_utils.find_viable_smart(smarts_t, "monster", nil, true)
				if ini_sys:section_exist(squad_sec) and smart then		-- check for spawned stuff on this smart here

					-- spawn squad
					local squad = spawn_raid_sim_squad(smart.id, squad_sec)

					-- store squad
					if squad then
						-- make it "idle" if possible
						if squads_t.mutants[preset][faction].idle > 0 then
							squad.scripted_target = smart:name()
							raid_squads_t[squad.id] = smart:name()
							squads_t.mutants[preset][faction].idle = squads_t.mutants[preset][faction].idle - 1
						else
							squad.idle_time = 0
							raid_squads_t[squad.id] = "walking"
						end
						printf("$ spawn mutant squad [%s] on smart [%s]", squad_sec, smart:name())
					end

					-- remove smart from the table (spawn 1 squad per smart)
					smarts_t[smart.id] = nil

				end
			end

		end
	end

end

function spawn_raid_sim_squad(smart_id, squad_sec)
--	local smart = SIMBOARD.smarts_by_names[smart_name]
	local smart = alife_object(smart_id)
	if not (smart and smart:clsid() == clsid.smart_terrain) then return end

	local squad = SIMBOARD:create_squad(smart, squad_sec)
	if not squad then return end

	squad.respawn_point_id = smart.id
	squad.respawn_point_prop_section = squad_sec
	for m in squad:squad_members() do
		SIMBOARD:setup_squad_and_group(m.object)
	end

	return squad
end

function squad_on_first_update(squad)		-- set idle time or scripted target again
	if raid_squads_t[squad.id] then
		if raid_squads_t[squad.id] == "walking" then
			squad.idle_time = 0
		else
			squad.scripted_target = raid_squads_t[squad.id]
		end
	end
end

function release_raid_sim_squads()
	for squad_id, _ in pairs(raid_squads_t) do
		local squad = alife_object(squad_id)
		if squad and squad.commander_id then
			alife_release(squad)
		end
	end

	empty_table(raid_squads_t)
end

-- disable all vanilla spawns on new game
function sim_board.simulation_board.fill_start_position(self)
end

-- disable all vanilla spawns from smarts
function on_try_respawn(se_obj, flags)
	flags.disabled = true
end

function actor_on_first_update()
	-- disable npc travelling between levels
	if simulation_objects and simulation_objects.ALLOW_NPC_LEVEL_TRANSITION then
		simulation_objects.ALLOW_NPC_LEVEL_TRANSITION = false
	end

	-- spawn sim (and event) npcs when in raid
	if (not raid_sim_spawned) and level.name() ~= raid_utils.raid_home_level then
		raid_sim_spawned = true

		raid_events.raid_start_event_spawn(level.name())
		raid_start_spawn(level.name())
	end

	-- release sim (and event) npcs when at home
	if raid_sim_spawned and level.name() == raid_utils.raid_home_level then
		raid_sim_spawned = false

		raid_events.raid_end_events()
		release_raid_sim_squads()
	end

end

-- store squads data to set idle time or scripted target again
function save_state(m_data)
	m_data.raid_squads_t = raid_squads_t
	m_data.raid_sim_spawned = raid_sim_spawned
end

function load_state(m_data)
	raid_squads_t = m_data.raid_squads_t or {}
	raid_sim_spawned = m_data.raid_sim_spawned or nil
end

-- TEST
local tmr = 0
function test_on_update()
	local tg = time_global()
	if tmr > tg then return end
	tmr = tg + 5000

	printf("---------------------------------")

	for squad_id, typ in pairs(raid_squads_t) do
		local squad = alife_object(squad_id)
		if squad then
			printf("id: %s || name: %s || type: %s || idle_time: %s", squad.id, squad:section_name(), typ, squad.idle_time)
		end
	end

	printf("---------------------------------")
end

function on_game_start()
	RegisterScriptCallback("squad_on_first_update", squad_on_first_update)
	RegisterScriptCallback("on_try_respawn", on_try_respawn)
	RegisterScriptCallback("actor_on_first_update", actor_on_first_update)
	RegisterScriptCallback("save_state", save_state)
	RegisterScriptCallback("load_state", load_state)

--	RegisterScriptCallback("actor_on_update", test_on_update)
end